import React, { useEffect, useState } from 'react';
import { db, isFirebaseConfigured } from '../firebaseClient';
import { collection, getDocs, addDoc, deleteDoc, doc, query, orderBy } from 'firebase/firestore';
import { ClipboardList, User, Users, Plus, Save, FileDown, Trash2 } from 'lucide-react';
import jsPDF from 'jspdf';
import ElementRecordsSection from '../components/ElementRecordsSection';

export default function Element4({ userRole }) {
  const [subTab, setSubTab] = useState('records'); // 'records' or 'reports'
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isFormOpen, setIsFormOpen] = useState(false);

  // Form states
  const [studentName, setStudentName] = useState('');
  const [classroom, setClassroom] = useState('');
  const [reportType, setReportType] = useState('individual');
  const [reportContent, setReportContent] = useState('');
  const [statusText, setStatusText] = useState('');

  const fetchReports = async () => {
    if (!isFirebaseConfigured()) {
      setLoading(false);
      return;
    }
    try {
      const q = query(collection(db, 'learning_reports'), orderBy('created_at', 'desc'));
      const querySnapshot = await getDocs(q);
      const list = [];
      querySnapshot.forEach(docSnap => {
        list.push({ id: docSnap.id, ...docSnap.data() });
      });
      setReports(list);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleSaveReport = async (e) => {
    e.preventDefault();
    if (userRole === 'visitor') return;

    setStatusText('กำลังบันทึกรายงาน...');
    try {
      await addDoc(collection(db, 'learning_reports'), {
        student_name: studentName,
        classroom: classroom,
        report_type: reportType,
        report_content: reportContent,
        created_at: new Date().toISOString()
      });

      setStatusText('บันทึกผลการเรียนรู้สำเร็จ!');
      setStudentName('');
      setClassroom('');
      setReportContent('');
      setIsFormOpen(false);
      fetchReports();
    } catch (err) {
      setStatusText('เกิดข้อผิดพลาด: ' + err.message);
    }
  };

  const handleDelete = async (id) => {
    if (userRole !== 'admin') {
      alert('เฉพาะผู้ดูแลระบบที่มีสิทธิ์ลบรายงานการเรียนรู้');
      return;
    }
    if (window.confirm('ยืนยันที่จะลบรายงานนี้?')) {
      try {
        await deleteDoc(doc(db, 'learning_reports', id));
        fetchReports();
      } catch (err) {
        alert(err.message);
      }
    }
  };

  const handleExportReportPDF = (report) => {
    const docObj = new jsPDF();
    docObj.setFont("Helvetica");

    docObj.setFontSize(16);
    docObj.text("RSPG Botanical School Learning Report Summary", 15, 20);

    docObj.setDrawColor(46, 125, 50);
    docObj.setLineWidth(0.5);
    docObj.line(15, 25, 195, 25);

    docObj.setFontSize(12);
    docObj.text(`Student: ${report.student_name}`, 15, 35);
    docObj.text(`Classroom: ${report.classroom}`, 15, 42);
    docObj.text(`Report Type: ${report.report_type === 'individual' ? 'Individual Student' : 'Classroom Session'}`, 15, 49);
    docObj.text(`Date Recorded: ${report.created_at?.split('T')[0]}`, 15, 56);

    docObj.text("Learning Details & Study Achievements:", 15, 70);
    docObj.setFontSize(10);
    docObj.text(report.report_content || 'No detailed content supplied', 15, 80, { maxWidth: 170 });

    docObj.setFontSize(8);
    docObj.setTextColor(120, 120, 120);
    docObj.text("Generated by RSPG school botanical garden web application", 15, 280);

    docObj.save(`Learning_Report_${report.student_name}.pdf`);
  };

  return (
    <div>
      {/* Intro info panel */}
      <div className="card glass-panel" style={{ marginBottom: '2rem' }}>
        <h3 style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--color-primary)', marginBottom: '0.5rem' }}>
          องค์ประกอบที่ 4: การรายงานผลการเรียนรู้
        </h3>
        <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
          เน้นการวิเคราะห์ สังเคราะห์ผลการเรียนรู้ นำเสนอรายงานวิชาการแสดงผลการเข้าชั้นเรียนศึกษา สรุปเนื้อหาการเก็บข้อมูลของนักเรียนแบบรายบุคคล หรือสรุปภาพรวมรายสัปดาห์/รายปีของห้องเรียน เพื่อวัดประเมินความสอดคล้องตามเกณฑ์ อพ.สธ.
        </p>

        {/* Sub Navigation Tabs */}
        <div style={{ display: 'flex', gap: '10px', marginTop: '1.5rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '1px' }}>
          <button
            type="button"
            onClick={() => setSubTab('records')}
            className={`btn ${subTab === 'records' ? 'btn-primary' : 'btn-secondary'}`}
            style={{ padding: '0.5rem 1rem', fontSize: '0.85rem' }}
          >
            <ClipboardList size={14} /> บันทึกกิจกรรมและหลักฐาน (6 ฟิลด์หลัก)
          </button>

          <button
            type="button"
            onClick={() => setSubTab('reports')}
            className={`btn ${subTab === 'reports' ? 'btn-primary' : 'btn-secondary'}`}
            style={{ padding: '0.5rem 1rem', fontSize: '0.85rem' }}
          >
            <Users size={14} /> ทำเนียบรายงานการเรียนรู้ของนักเรียน ({reports.length})
          </button>
        </div>
      </div>

      {subTab === 'records' ? (
        <ElementRecordsSection elementNum={4} userRole={userRole} />
      ) : (
        <>
          {userRole !== 'visitor' && !isFormOpen && (
            <button onClick={() => setIsFormOpen(true)} className="btn btn-primary" style={{ marginBottom: '1.5rem' }}>
              <Plus size={16} /> บันทึกรายงานการเรียนรู้เพิ่ม
            </button>
          )}

      {isFormOpen && (
        <div className="card" style={{ marginBottom: '2rem' }}>
          <h3 className="card-title">บันทึกชั่วโมงเรียน/ผลการศึกษาพฤกษศาสตร์ใหม่</h3>
          <form onSubmit={handleSaveReport}>
            <div className="grid-3">
              <div className="form-group">
                <label className="form-label">ชื่อนักเรียน / กลุ่มศึกษา</label>
                <input
                  type="text"
                  className="form-control"
                  placeholder="เช่น ด.ช. วิทยู มีสุข"
                  value={studentName}
                  onChange={(e) => setStudentName(e.target.value)}
                  required
                />
              </div>

              <div className="form-group">
                <label className="form-label">ชั้นเรียน (Classroom)</label>
                <input
                  type="text"
                  className="form-control"
                  placeholder="เช่น ม.3/1"
                  value={classroom}
                  onChange={(e) => setClassroom(e.target.value)}
                  required
                />
              </div>

              <div className="form-group">
                <label className="form-label">รูปแบบรายงาน</label>
                <select
                  className="form-control"
                  value={reportType}
                  onChange={(e) => setReportType(e.target.value)}
                >
                  <option value="individual">รายงานสรุปรายบุคคล</option>
                  <option value="classroom">รายงานสรุปรายห้องเรียน</option>
                </select>
              </div>
            </div>

            <div className="form-group">
              <label className="form-label">สรุปเนื้อหาผลการเรียนรู้ / องค์ความรู้ที่ได้รับ</label>
              <textarea
                className="form-control"
                rows="4"
                placeholder="ระบุสิ่งที่เรียนรู้ สรรพคุณ หรือวิเคราะห์สัณฐานพืชอย่างย่อ..."
                value={reportContent}
                onChange={(e) => setReportContent(e.target.value)}
                required
              ></textarea>
            </div>

            {statusText && (
              <div style={{ padding: '0.75rem', borderRadius: '6px', backgroundColor: 'rgba(46,125,50,0.1)', color: 'var(--color-success)', fontSize: '0.85rem', marginBottom: '1rem' }}>
                {statusText}
              </div>
            )}

            <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end' }}>
              <button type="button" onClick={() => setIsFormOpen(false)} className="btn btn-secondary">ยกเลิก</button>
              <button type="submit" className="btn btn-primary">บันทึกรายงาน</button>
            </div>
          </form>
        </div>
      )}

      {/* Reports Listing */}
      <div className="card">
        <h3 className="card-title">
          <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <ClipboardList size={20} color="var(--color-orchid)" />
            ทำเนียบผลงานและรายงานกิจกรรมการเรียนรู้ของนักเรียน
          </span>
        </h3>

        {loading ? (
          <div style={{ textAlign: 'center', padding: '2rem' }}>กำลังดาวน์โหลดผลงาน...</div>
        ) : reports.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-muted)' }}>
            ยังไม่พบประวัติผลงานนักเรียนในระบบ
          </div>
        ) : (
          <div className="table-container" style={{ marginTop: 0 }}>
            <table className="custom-table" style={{ fontSize: '0.88rem' }}>
              <thead>
                <tr>
                  <th>ประเภท</th>
                  <th>ผู้นำเสนอ/ผู้สรุป</th>
                  <th>ชั้นเรียน</th>
                  <th>เนื้อหาสรุปความรู้</th>
                  <th>วันที่บันทึก</th>
                  <th>การจัดการ</th>
                </tr>
              </thead>
              <tbody>
                {reports.map(report => (
                  <tr key={report.id}>
                    <td>
                      <span className="role-badge" style={{
                        backgroundColor: report.report_type === 'individual' ? 'rgba(46,125,50,0.08)' : 'rgba(186,85,211,0.08)',
                        color: report.report_type === 'individual' ? 'var(--color-primary)' : 'var(--color-orchid)'
                      }}>
                        <User size={12} />
                        {report.report_type === 'individual' ? 'รายบุคคล' : 'รายห้อง'}
                      </span>
                    </td>
                    <td style={{ fontWeight: 'bold' }}>{report.student_name}</td>
                    <td>{report.classroom}</td>
                    <td style={{ maxWidth: '300px', fontSize: '0.82rem', color: 'var(--text-muted)' }}>
                      {report.report_content?.substring(0, 80)}...
                    </td>
                    <td>{report.created_at?.split('T')[0]}</td>
                    <td>
                      <div style={{ display: 'flex', gap: '5px' }}>
                        <button onClick={() => handleExportReportPDF(report)} className="icon-btn" style={{ width: '32px', height: '32px' }} title="ดาวน์โหลด PDF">
                          <FileDown size={14} color="var(--color-primary)" />
                        </button>
                        {userRole === 'admin' && (
                          <button onClick={() => handleDelete(report.id)} className="icon-btn" style={{ width: '32px', height: '32px' }} title="ลบข้อมูล">
                            <Trash2 size={14} color="var(--color-danger)" />
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </>
  )}
</div>
  );
}
